// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXBvrYCPR4RWMIpQcf0S3O6dIn8XhR75w',
    appId: '1:610788374230:web:4f681945134d771750fb77',
    messagingSenderId: '610788374230',
    projectId: 'crud1-e17cc',
    authDomain: 'crud1-e17cc.firebaseapp.com',
    storageBucket: 'crud1-e17cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArx9BkfUo3EzHWjDEg5R5NLsetjpjwpSE',
    appId: '1:610788374230:android:f4b7edce6639df1950fb77',
    messagingSenderId: '610788374230',
    projectId: 'crud1-e17cc',
    storageBucket: 'crud1-e17cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoG8sWgxdOa8O1mxsSmHIFz-V_0T0JjoI',
    appId: '1:610788374230:ios:62bb48a78269026d50fb77',
    messagingSenderId: '610788374230',
    projectId: 'crud1-e17cc',
    storageBucket: 'crud1-e17cc.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );
}
